name: AppHatch Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Build and run Docker container
        run: |
          docker compose -f docker/docker-compose.yml build
          docker compose -f docker/docker-compose.yml up -d

      - name: Fetch built binaries
        run: |
          sudo chmod +x scripts/fetch-builds.sh
          scripts/fetch-builds.sh
      
      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: apphatch-debian-${{ github.ref_name }}
          path: target/*.deb

      - name: Upload RPM package
        uses: actions/upload-artifact@v4
        with:
          name: apphatch-fedora-${{ github.ref_name }}
          path: target/*.rpm

      - name: Upload Arch package
        uses: actions/upload-artifact@v4
        with:
          name: apphatch-arch-${{ github.ref_name }}
          path: target/*.pkg.tar.zst

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: AppHatch ${{ github.ref_name }}
          body: |
            ## AppHatch ${{ github.ref_name }}
            
            ### Downloads
            - **Debian/Ubuntu**: `apphatch_${{ github.ref_name }}_amd64.deb`
            - **Fedora/RHEL**: `apphatch-${{ github.ref_name }}-1.x86_64.rpm`
            - **Arch Linux**: `apphatch-bin-${{ github.ref_name }}-1-x86_64.pkg.tar.zst`
            
            ### Installation
            
            **Debian/Ubuntu:**
            ```bash
            sudo dpkg -i apphatch_${{ github.ref_name }}_amd64.deb
            ```
            
            **Fedora/RHEL:**
            ```bash
            sudo rpm -i apphatch-${{ github.ref_name }}-1.x86_64.rpm
            ```
            
            **Arch Linux:**q
            ```bash
            sudo pacman -U apphatch-bin-${{ github.ref_name }}-1-x86_64.pkg.tar.zst
            ```
          files: |
            apphatch-debian-${{ github.ref_name }}/*.deb
            apphatch-fedora-${{ github.ref_name }}/*.rpm
            apphatch-arch-${{ github.ref_name }}/*.pkg.tar.zst
          draft: false
          prerelease: false

